name: EShop
services:
  catalogdb:
    image: mongo  

  basketdb:
    image: redis:alpine

  discountdb:
    image: postgres

  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  portainer:
    image: portainer/portainer-ce

  pgadmin:
    image: dpage/pgadmin4
  
  rabbitmq:
    image: rabbitmq:3-management-alpine

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.2

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
   
  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
      
  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  pgadmin_data:
  redis_data:
  postgres_data:  
  orderdb-data:  
  elasticsearch-data:
